version: '1'
services:
  odoo: # ODOO SERVICE NAME
    image: odoo:16 # ODOO VERSION
    depends_on:
      - db # POSTGRES INSTANCE NAME
    ports:
      - "8070:8069" # ODOO PORT | HOST_PORT:CONTAINER_PORT
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ../shared:/mnt/shared-addons
    # command: odoo -c /etc/odoo/odoo.conf
    ### command to use while executing odoo-bin
    ### ex:
    ### -u MODULE_NAME : update module
  db: # POSTGRES SERVICE NAME
    image: postgres:16 # POSTGRES VERSION
    ports:
      - "5433:5432" # POSTGRES PORT | HOST_PORT:CONTAINER_PORT
	environment:
	  - POSTGRES_DB=POSTGRES_DATABASE
	  - POSTGRES_USER=POSTGRES_USER
	  - POSTGRES_PASSWORD=POSTGRES_PASSWORD
	  - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  data:
  db: